Repository proxmoxer/proxmoxer, pull requests merged in 2021-05, with the labels that each got.

#51 Update README.rst
  README.rst
Labels: type:docs :memo:

#55 Fix String-based path
  proxmoxer/core.py
Labels: type:breaking, type:enhancement :arrow_double_up:

#58 Use GitHub default python gitignore with additions
  .gitignore
Labels: type:maintenance :hammer_and_wrench:

#57 Allow responses which are not JSON to be handled
  proxmoxer/backends/base_ssh.py
  proxmoxer/backends/https.py
  proxmoxer/core.py
Labels: type:enhancement :arrow_double_up:

#59 Add devcontainer support for easier development
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .vscode/settings.json
  dev_requirements.txt
  proxmoxer/backends/https.py
Labels: type:enhancement :arrow_double_up:, type:maintenance :hammer_and_wrench:
