Repository proxmoxer/proxmoxer, pull requests merged in 2022-08, with the labels that each got.

#108 Remove ProxmoxResourceBase
  proxmoxer/core.py
Labels: type:maintenance :hammer_and_wrench:

#109 Allow specifying resource_id as 0 for firewall rule compatibility
  proxmoxer/core.py
Labels: type:bug :lady_beetle:, backend:https, backend:openssh, backend:ssh_paramiko, backend:local

#110 Convert to pytest
  .bandit
  .coveragerc
  .devcontainer/devcontainer.json
  .devcontainer/setup.sh
  .github/workflows/ci.yaml
  .pre-commit-config.yaml
  .travis.yml
  .vscode/settings.json
  .vscode/tasks.json
  proxmoxer/backends/command_base.py
  proxmoxer/backends/https.py
  proxmoxer/backends/openssh.py
  proxmoxer/backends/ssh_paramiko.py
  proxmoxer/core.py
  setup.cfg
  setup.py
  test_requirements.txt
  tests/__init__.py
  tests/api_mock.py
  tests/base/__init__.py
  tests/base/base_suite.py
  tests/https_helpers_tests.py
  tests/https_tests.py
  tests/known_issues.json
  tests/local_tests.py
  tests/openssh_tests.py
  tests/paramiko_tests.py
  tests/test_command_base.py
  tests/test_core.py
  tests/test_https.py
  tests/test_https_helpers.py
  tests/test_imports.py
  tests/test_local.py
  tests/test_openssh.py
  tests/test_paramiko.py
Labels: type:testing :test_tube:
